Repository OffchainLabs/arbitrum-docs, pull requests merged in 2024-07, with the labels that each got.

#1410 feat: remove banner
  website/docusaurus.config.js
Labels: s

#1407 docs: add initial arbos 30 bianca docs
  arbitrum-docs/audit-reports.mdx
  arbitrum-docs/run-arbitrum-node/arbos-releases/01-overview.md
  arbitrum-docs/run-arbitrum-node/arbos-releases/arbos11.md
  arbitrum-docs/run-arbitrum-node/arbos-releases/arbos20.md
  arbitrum-docs/run-arbitrum-node/arbos-releases/arbos30.md
  website/sidebars.js
Labels: s

#1301 Update oracles section
  arbitrum-docs/build-decentralized-apps/oracles/02-how-to-use-oracles.md
Labels: s

#1394 docs: typo fix for missing space between words
  arbitrum-docs/how-arbitrum-works/bold/gentle-introduction.md
Labels: s

#1327 Add note about registering a custom token in the Token Bridge of a custom-gas-token Orbit chain
  arbitrum-docs/launch-orbit-chain/concepts/custom-gas-token-sdk.md
Labels: s

#1337 Add note about gas limits on Ethereum vs Arbitrum
  arbitrum-docs/build-decentralized-apps/arbitrum-vs-ethereum/02-block-numbers-and-time.md
  website/sidebars.js
Labels: s

#1417 add forwarding url to orbit node running
  arbitrum-docs/node-running/how-tos/running-an-orbit-node.mdx
Labels: s

#1385 docs for using the graph on arbitrum
  arbitrum-docs/for-devs/third-party-docs/TheGraph/thegraph.md
Labels: s

#1429 Update infra-options-orbit-chains.md
  arbitrum-docs/launch-orbit-chain/infra-options-orbit-chains.md
Labels: s

#1401 feat: Add Stylus Caching Strategy Concept Page
  arbitrum-docs/stylus/concepts/stylus-cache-manager.md
  website/sidebars.js
Labels: s, Status: Editorial review

#1428 Add Nova to nodes provided by Alchemy + format
  arbitrum-docs/build-decentralized-apps/arbitrum-vs-ethereum/02-block-numbers-and-time.md
  arbitrum-docs/build-decentralized-apps/reference/01-node-providers.md
  arbitrum-docs/how-arbitrum-works/bold/gentle-introduction.md
  arbitrum-docs/run-arbitrum-node/arbos-releases/arbos30.md
  arbitrum-docs/stylus/reference/testnet-information.md
  website/src/css/partials/_variables.scss
Labels: s

#1319 Update customize-precompile.mdx
  arbitrum-docs/launch-orbit-chain/how-tos/customize-precompile.mdx
Labels: s

#1416 Update FAQs
  arbitrum-docs/partials/_glossary-partial.md
  arbitrum-docs/partials/_troubleshooting-building-partial.md
  arbitrum-docs/partials/_troubleshooting-orbit-partial.md
  website/static/building-faqs.json
  website/static/building-orbit-faqs.json
  website/static/glossary.json
Labels: s, Status: Pending modifications approval

#1438 Fix broken link to Bwarelabs sepolia faucet
  arbitrum-docs/stylus/stylus-quickstart.md
Labels: s

#1290 Add orbit validator setting docs
  arbitrum-docs/run-arbitrum-node/more-types/02-run-validator-node.md
  website/sidebars.js
Labels: s, Status: Pending modifications approval

#1431 Add missing word 'find' in the overview paragraph
  arbitrum-docs/build-decentralized-apps/arbitrum-vs-ethereum/01-comparison-overview.md
Labels: s

#1444 Update website/package.json` to avoid compile errors
  website/package.json
Labels: s

#1445 feat: add stylus-by-example in sidebar
  website/sidebars.js
Labels: s

#1500 docs: add annual reactivation requirement for stylus contracts to caching docs
  arbitrum-docs/stylus/concepts/stylus-cache-manager.md
Labels: s

#1463 feat: Add guide for debugging Stylus transactions with Cargo Stylus Replay
  arbitrum-docs/stylus/concepts/stylus-cache-manager.md
  arbitrum-docs/stylus/how-tos/debugging-stylus-tx.mdx
  website/sidebars.js
Labels: s

#1496 Update go and node version for building nitro locally
  arbitrum-docs/run-arbitrum-node/nitro/01-build-nitro-locally.md
Labels: s

#1502 Update nitro version to v3.1.0
  website/src/resources/globalVars.js
Labels: s

#1505 Add new security audit reports
  arbitrum-docs/audit-reports.mdx
  arbitrum-docs/hosted-audit-reports/2024-04-offchain-arbos-30-nitro-upgrade-securityreview.pdf
  arbitrum-docs/hosted-audit-reports/2024-04-offchain-arbos-31-securityreview.pdf
  arbitrum-docs/hosted-audit-reports/2024-04-offchain-l1-l3-teleporter-securityreview.pdf
  arbitrum-docs/hosted-audit-reports/2024-04-offchainbold-securityreview.pdf
  arbitrum-docs/hosted-audit-reports/2024-05-offchain-arbitrumstylus-securityreview.pdf
  arbitrum-docs/hosted-audit-reports/ConsenSys_Diligence_Arbitrum_Contracts_11_2021.pdf
  arbitrum-docs/hosted-audit-reports/ConsenSys_Diligence_Nitro_Contracts_5_2022.pdf
  arbitrum-docs/hosted-audit-reports/Trail_Of_Bits_Nitro_10_2022.pdf
  arbitrum-docs/hosted-audit-reports/trail_of_bits_governance_report_1_6_2023.pdf
Labels: s

#1512 feat: update pdf doc > arbos30 security report
  arbitrum-docs/hosted-audit-reports/2024-04-offchain-arbos-30-nitro-upgrade-securityreview.pdf
Labels: s

#1511 Add caption to OG diagram from Ed Felten
  arbitrum-docs/how-arbitrum-works/inside-arbitrum-nitro.md
  website/src/components/ImageCaptions/index.jsx
Labels: s

#1499 Create openfort.md
  arbitrum-docs/for-devs/third-party-docs/Openfort/openfort.md
Labels: s

#1514 Removal stale placeholder DAC configuration
  arbitrum-docs/run-arbitrum-node/data-availability-committees/01-get-started.md
  arbitrum-docs/run-arbitrum-node/data-availability-committees/04-configure-dac.md
  website/sidebars.js
Labels: s

#1517 Typo in execution.forwarding-target
  arbitrum-docs/node-running/how-tos/running-an-orbit-node.mdx
Labels: s

#1513 Update arbos30 31 security audit report
  arbitrum-docs/audit-reports.mdx
  arbitrum-docs/hosted-audit-reports/2024-04-offchain-arbos-31-securityreview.pdf
Labels: s

#1501 docs: add stylus reactivation faq section
  arbitrum-docs/partials/_troubleshooting-stylus-partial.md
Labels: s
