Repository OffchainLabs/arbitrum-docs, pull requests merged in 2025-07, with the labels that each got.

#2426 add classic node performance note
  arbitrum-docs/run-arbitrum-node/more-types/03-run-classic-node.mdx
Labels: Needs SME review

#2487 Update building nitro docs for go 1.24
  docs/run-arbitrum-node/nitro/01-build-nitro-locally.mdx
Labels: Needs SME review, no merge conflict

#2388 Add "testing your contract " section to Stylus' Quick start.
  docs/stylus/quickstart.mdx
Labels: Needs SME review, no merge conflict

#2485 fix sqm pictures and add a line to explain seq's url to add
  docs/run-arbitrum-node/sequencer/03-run-sequencer-coordination-manager.mdx
  static/img/run-node-add-to-priority.png
  static/img/run-node-change-priority.png
  static/img/run-node-seq-coordinator-manager.png
Labels: no merge conflict

#2452 Stylus constructors
  docs/stylus/how-tos/using-constructors.mdx
Labels: Needs SME review, no merge conflict

#2500 add notice about eip2537 to arbos40 callisto
  .github/dependabot.yml
  README.md
  docs/launch-arbitrum-chain/concepts/_category_.yml
  docs/launch-arbitrum-chain/how-tos/_category_.yml
  docs/launch-arbitrum-chain/reference/_category_.yml
  docs/node-running/how-tos/data-availability-committee/_category_.yml
  docs/node-running/reference/_category_.yml
  docs/partials/_troubleshooting-stylus-partial.mdx
  docs/run-arbitrum-node/arbos-releases/arbos40.mdx
  docs/stylus/concepts/_category_.yml
  docs/stylus/how-tos/_category_.yml
  docs/stylus/reference/_category_.yml
  notion-docs/tsconfig.json
  scripts/check-globalvars-updates.ts
  scripts/check-redirects.ts
  src/components/InteractiveDiagrams/Timeboost/CentralizedAuction/NumberComponent.jsx
  src/components/InteractiveDiagrams/Timeboost/CentralizedAuction/index.jsx
  src/components/MermaidWithHtml/MermaidWithHtml.css
  src/components/MermaidWithHtml/MermaidWithHtml.jsx
  src/components/MermaidWithHtml/MermaidWithHtml.less
  src/components/PlaceholderForm/PlaceholderForm.jsx
  src/components/VanillaAdmonition/styles.module.css
  static/bridging-faqs.json
  static/building-faqs.json
  static/building-orbit-faqs.json
  static/building-stylus-faqs.json
  static/get-started-faqs.json
  static/glossary.json
  static/node-running-faqs.json
  vitest.config.ts
Labels: no merge conflict
