Repository OffchainLabs/arbitrum-docs, pull requests merged in 2025-01, with the labels that each got.

#1947 docs: fixing-inbox-contract-broken-link
  arbitrum-docs/how-arbitrum-works/10-l1-to-l2-messaging.mdx
Labels: s

#1893 Update infra-options-orbit-chains.md
  arbitrum-docs/launch-orbit-chain/infra-options-orbit-chains.md
Labels: blocked-on-cla

#1954 Add stringStorage setter and getter tu stylus-sdk-guide
  arbitrum-docs/stylus/reference/rust-sdk-guide.md
Labels: s

#1955 docs: updated-dac-links-to-hyperlinks
  arbitrum-docs/launch-orbit-chain/infra-options-orbit-chains.md
Labels: s

#1957 update min nitro version for arbos32
  arbitrum-docs/run-arbitrum-node/arbos-releases/arbos32.mdx
Labels: s

#1958 docs: quickfix-submit-tx-to-sequencer-infographic
  arbitrum-docs/assets/submit-tx-to-sequencer.png
Labels: s

#1959 docs: new-seq-graphic
  arbitrum-docs/assets/submit-tx-to-sequencer.png
Labels: s

#1224 Update orbit-gentle-introduction.md
  arbitrum-docs/launch-orbit-chain/orbit-gentle-introduction.md
Labels: Status: Pending portal review

#1551 File module root filename in customize-stf.mdx
  arbitrum-docs/launch-orbit-chain/how-tos/customize-stf.mdx
Labels: s

#1965 Update stylus rust dep
  arbitrum-docs/stylus/quickstart.mdx
  arbitrum-docs/stylus/using-cli.mdx
Labels: s

#1802 gmehta-Update fast-withdrawals.mdx
  arbitrum-docs/launch-orbit-chain/how-tos/fast-withdrawals.mdx
Labels: s

#1842 Update infra-options-orbit-chains.md
  arbitrum-docs/launch-orbit-chain/infra-options-orbit-chains.md
Labels: s

#1930 Update 01-comparison-overview.mdx
  arbitrum-docs/build-decentralized-apps/arbitrum-vs-ethereum/01-comparison-overview.mdx
Labels: blocked-on-cla

#1966 docs: adding-webacy-to-third-party-docs
  arbitrum-docs/for-devs/third-party-docs/Webacy/webacy.md
Labels: s

#1964 docs: add-pyth-as-oracle
  arbitrum-docs/for-devs/oracles/oracles-content-map.mdx
  arbitrum-docs/for-devs/oracles/pyth/pyth.mdx
Labels: s

#1892 How to run a full node for an Orbit chain: added missing flag for anytrust chains
  arbitrum-docs/node-running/how-tos/running-an-orbit-node.mdx
Labels: blocked-on-cla

#1699 Update 03-public-chains.md - Grammatical Typo
  arbitrum-docs/build-decentralized-apps/03-public-chains.mdx
Labels: Status: Pending CLA

#1963 AEP scripts tutorial
  arbitrum-docs/launch-orbit-chain/how-tos/set-up-aep-fee-router.mdx
Labels: s

#1939 Upload audit report file and update audits table (Bold Fixes)
  arbitrum-docs/audit-reports.mdx
  arbitrum-docs/hosted-audit-reports/2024_12_26_trail_of_bits_boldfixes_securityreview.pdf
Labels: s

#1772 Add how to use timeboost
  arbitrum-docs/run-arbitrum-node/how-to-use-timeboost.mdx
  arbitrum-docs/run-arbitrum-node/sequencer/02-read-sequencer-feed.mdx
  website/sidebars.js
Labels: s
